ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

HB_PRGFLAGS += -gc3

#dummy.c
C_SOURCES := \
   addascii.c \
   asciisum.c \
   ascpos.c \
   atadjust.c \
   atnum.c \
   atrepl.c \
   bitnum.c \
   bitstr.c \
   blank.c \
   charevod.c \
   charlihb.c \
   charlist.c \
   charmirr.c \
   charmix.c \
   charone.c \
   charonly.c \
   charop.c \
   charophb.c \
   charrepl.c \
   charsort.c \
   charsprd.c \
   charswap.c \
   color.c \
   count.c \
   ctc.c \
   ctchksum.c \
   ctcom1.c \
   ctcom2.c \
   ctcrypt.c \
   ctmath2.c \
   ctmath.c \
   ctnet.c \
   ctpad.c \
   ctstr.c \
   ctstrfil.c \
   ctwfunc.c \
   ctwin.c \
   cursor.c \
   datetime.c \
   dattime2.c \
   dattime3.c \
   dbfflddc.c \
   dbftools.c \
   disk.c \
   envparam.c \
   expand.c \
   exponent.c \
   files.c \
   finan.c \
   ftoc.c \
   justify.c \
   keyset.c \
   like.c \
   lton.c \
   maxline.c \
   misc1.c \
   misc2.c \
   misc3.c \
   misc4.c \
   num1.c \
   numat.c \
   numbase.c \
   numcount.c \
   numline.c \
   pack.c \
   pos1.c \
   pos2.c \
   posdiff.c \
   print.c \
   range.c \
   relation.c \
   remove.c \
   replace.c \
   screen1.c \
   screen2.c \
   setlast.c \
   setrc.c \
   strdiff.c \
   strswap.c \
   tab.c \
   token1.c \
   token2.c \
   trig.c \
   video.c \
   wordrepl.c \
   wordtoch.c \
   xhbfunc.c \

PRG_SOURCES := \
   ctdummy.prg \
   ctmisc.prg \
   ctrand.prg \
   cttime.prg \
   fcopy.prg \
   getinfo.prg \
   getinput.prg \
   getsecrt.prg \
   keysave.prg \
   keysec.prg \
   keytime.prg \
   kxlat.prg \
   screen3.prg \
   scrmark.prg \
   showtime.prg \
   tempfile.prg \

LIBNAME := hbct

include $(TOP)$(ROOT)config/lib.mk

