ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

HB_PRGFLAGS += -gc3

C_SOURCES := \
   encurlc.c \
   mime.c \
   misc.c \

PRG_SOURCES := \
   base64u.prg \
   cgi.prg \
   client.prg \
   encb64.prg \
   encoder.prg \
   encqp.prg \
   encurl.prg \
   ftpcli.prg \
   httpcli.prg \
   log.prg \
   mailassy.prg \
   mail.prg \
   mailsend.prg \
   popcli.prg \
   sessid.prg \
   smtpcli.prg \
   thtml.prg \
   url.prg \

LIBNAME := hbtip

include $(TOP)$(ROOT)config/lib.mk

