IF NOT DEFINED WINSDK_VER set WINSDK_VER=10.0.18362.0
set LIBRARY=uuid
set LIB_SOURCE_DIR=uuid-1.6.2-win32-patched
set BUILD_ARCH=x86
set VCTOOLS_ARCH=x86
set ROOT_DIR=\users\%USERNAME%\harbour

IF NOT DEFINED UUID_BUILD set INCLUDE=
IF NOT DEFINED UUID_BUILD set LIBPATH=
IF NOT DEFINED UUID_BUILD set PATH=c:\windows;c:\windows\system32

REM amd64 ili x86
IF NOT DEFINED UUID_BUILD call %VCBUILDTOOLS_PATH% %VCTOOLS_ARCH%

IF NOT DEFINED UUID_BUILD SET PATH=%PATH%;%PERL_C_BIN_PATH%
IF NOT DEFINED UUID_BUILD set PATH=%PATH%;%PERL_BIN_PATH%
IF NOT DEFINED UUID_BUILD set PATH=%PATH%;%PERL_SITE_BIN_PATH%
IF NOT DEFINED UUID_BUILD set PATH=%PATH%;C:\Program Files\Git\cmd
IF NOT DEFINED UUID_BUILD set PATH=%PATH%;C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\bin
IF NOT DEFINED UUID_BUILD set PATH=%PATH%;C:\Program Files (x86)\Windows Kits\10\bin\%WINSDK_VER%\%BUILD_ARCH%
set UUID_BUILD=1


set LIB_TARGET=%ROOT_DIR%\3rd\%BUILD_ARCH%\%LIBRARY%
set HB_INSTALL_PREFIX=%ROOT_DIR%\build\%BUILD_ARCH%\harbour

cd %ROOT_DIR%\3rd\%LIBRARY%\%LIB_SOURCE_DIR%

nmake -f Makefile.win32 clean
nmake -f Makefile.win32

mkdir %ROOT_DIR%\3rd\%BUILD_ARCH%
mkdir %LIB_TARGET%
mkdir %LIB_TARGET%\include
mkdir %LIB_TARGET%\lib

copy *.h %LIB_TARGET%\include
copy Release\*.lib %LIB_TARGET%\lib

cd %ROOT_DIR%\3rd\%LIBRARY%

dir /s %LIB_TARGET%
