#!/bin/bash

export GIT_REPOS=harbour
export BUILD_ARCH=x64
export ROOT_DIR=/home/$USERNAME/$GIT_REPOS
echo ROOT_DIR=/home/$USERNAME/$GIT_REPOS
export ROOT_3RD=$ROOT_DIR/3rd/$BUILD_ARCH

export LIB_BIN_ROOT=$ROOT_DIR/3rd/$BUILD_ARCH
echo LIB_BIN_ROOT=$LIB_BIN_ROOT

