#!/bin/bash

export GIT_REPOS=harbour
export BUILD_ARCH=x64
export ROOT_DIR=/home/$USERNAME/$GIT_REPOS
echo ROOT_DIR=/home/$USERNAME/$GIT_REPOS
export ROOT_3RD=$ROOT_DIR/3rd/$BUILD_ARCH

export LIB_BIN_ROOT=$ROOT_DIR/3rd/$BUILD_ARCH
echo LIB_BIN_ROOT=$LIB_BIN_ROOT

export HB_INSTALL_PREFIX=$ROOT_DIR/build/$BUILD_ARCH/harbour
echo HB_INSTALL_PREFIX=$HB_INSTALL_PREFIX

LD_LIBRARY_PATH="$ROOT_3RD/zlib/lib"
LD_LIBRARY_PATH+=":$ROOT_3RD/libxml2/lib"
LD_LIBRARY_PATH+=":$ROOT_3RD/libxslt/lib"
LD_LIBRARY_PATH+=":$ROOT_3RD/openssl/lib"
LD_LIBRARY_PATH+=":$ROOT_3RD/postgresql/lib"

export LD_LIBRARY_PATH

echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
