ROOT := ../../../

PRG_SOURCES := \
   arrayrdd.prg \
   dbtcdx.prg \
   fptcdx.prg \
   hscdx.prg \
   logrdd.prg \
   rlcdx.prg \
   smtcdx.prg \
   vfpcdx.prg \


LIBNAME := rddmisc

include $(TOP)$(ROOT)config/lib.mk
