IF NOT DEFINED WINSDK_VER set WINSDK_VER=10.0.18362.0
set LIBRARY=openssl
set LIB_SOURCE_DIR=OpenSSL_1_1_0l
set GIT_NAME=harbour
set ROOT_DIR=\users\%USERNAME%\%GIT_NAME%
set LIB_TARGET=%ROOT_DIR%\3rd\%BUILD_ARCH%\%LIBRARY%
set HB_INSTALL_PREFIX=%ROOT_DIR%\build\%BUILD_ARCH%\harbour

IF NOT DEFINED OPENSSL_BUILD set INCLUDE=
IF NOT DEFINED OPENSSL_BUILD set LIBPATH=
IF NOT DEFINED OPENSSL_BUILD set PATH=c:\windows;c:\windows\system32
IF NOT DEFINED OPENSSL_BUILD call %VCBUILDTOOLS_PATH%  %VCBUILDTOOLS%
IF NOT DEFINED OPENSSL_BUILD set PATH=%PATH%;C:\Program Files\Git\cmd
IF NOT DEFINED OPENSSL_BUILD set PATH=%PATH%;C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\bin
IF NOT DEFINED OPENSSL_BUILD set PATH=%PATH%;C:\Program Files (x86)\Windows Kits\10\bin\%WINSDK_VER%\%BUILD_ARCH%
IF NOT DEFINED OPENSSL_BUILD SET PATH=%PATH%;%PERL_C_BIN_PATH%
IF NOT DEFINED OPENSSL_BUILD set PATH=%PATH%;%PERL_BIN_PATH%
IF NOT DEFINED OPENSSL_BUILD set PATH=%PATH%;%PERL_SITE_BIN_PATH%
IF NOT DEFINED OPENSSL_BUILD SET PATH=%PATH%;%ROOT_DIR%\tools\win32\%NASM_DIR%
SET OPENSSL_BUILD=1

echo == cd %ROOT_DIR%\3rd\%LIBRARY%\%LIB_SOURCE_DIR% ========
cd %ROOT_DIR%\3rd\%LIBRARY%\%LIB_SOURCE_DIR%

git clean -x -d -f .

perl Configure --prefix=%LIB_TARGET% --openssldir=%LIB_TARGET% %OPENSSL_ARCH%
nmake -f makefile clean install

git checkout -f .
cd %ROOT_DIR%\3rd\%LIBRARY%

echo == %LIB_TARGET% ==
dir /s %LIB_TARGET%
