ROOT := ../../

include $(TOP)$(ROOT)config/global.mk

HB_PRGFLAGS += -gc3

C_SOURCES := \
   corec. \
 
PRG_SOURCES := \
   core.prg \
   table.prg \

LIBNAME := hbtest

include $(TOP)$(ROOT)config/lib.mk

